### ISSUE TITLE
7/24

### ISSUE THREAD

**Issue by ptq124** [ptq124/fe-newsstand#18]
## Todo
- [x] 리팩토링 리스트 정하기
- [x] 옵저버 패턴 고민
- [x] 뉴스 리스트 동작 오류 개선
