### ISSUE TITLE
7/18

### ISSUE THREAD

**Issue by ptq124** [ptq124/fe-newsstand#8]
## Todo
- [x] 리스트보기 hover이벤트
- [x] 구독하기 기능 구현
- [ ] 스낵바 UI 구현
- [ ]  내가 구독한 언론사 리스트 UI 구현

## 이슈
리스트 보기 UI를 어느정도 완성했지만, 계속 구현을 하게 되면 필연적으로 여러가지 이벤트를 어떻게 관리해야 하는지에 문제가 생길수 있다. 
작동하는 이벤트들이 여러개이고 동일 컴포넌트에 다른 기능을 하는 이벤트들이 존재했다. 
그래서 이벤트 핸들러를 효율적이르 관리하기 위헤 Store와 같은 중앙 집중적으로 관리하는 방법을 고민했다. 
옵저버 패턴, 이벤트 버스 패턴등 여러가지 패턴과 방법등이 있었지만 패턴에 집중하기 보단 store를 활용하여 한곳에서 관리하는 방법을 고민해 봐야겠다.
